spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation:true
  datasource:
    url: jdbc:postgresql://46.36.217.103:5432/emplist
    username: postgres
    password: 12345678
  thymeleaf:
    check-template-location: true
    suffix: .html
