spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation:true
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost/emplist
    username: postgres
    password: Postgres

  thymeleaf:
    check-template-location: true
    suffix: .html
